POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Syam",
  "email": "syam@gmail.com"
}

###

GET http://localhost:8080/users

###

PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Syam Satish",
  "email": "syam.satish@gmail.com"
}

###

DELETE http://localhost:8080/users/2